eclipse-score/score

- CONTRIBUTION.md
Change link locations from .rst to .html files in the initial commit
Issue-ref: resolves #1
> init: update initial links

- .github/workflows/docs.yml
> workflows: disable comment posting for forks

- docs/features/infrastructure/config_as_code.rst
- docs/features/infrastructure/index.rst
> docs: add config-as-code docs

- docs/features/integration/index.rst
This PR adds a description what is that role of incubation repositories.
> Proposal for incubation repositories

- docs/features/integration/index.rst
This PR describes the role and usage of incubation repositories.
Update after discussion with @masc2023, @aschemmel-tech, @LittleHuba 
Issue-ref: see #56
> docs: fix description of incubation repos

- docs/_extensions/metamodel.py
- docs/process/index.rst
- docs/process/roles/index.rst
- docs/process/roles/roles.rst
> docs: add process roles

- docs/features/frameworks/fixed-execution-order/index.rst
- docs/features/frameworks/index.rst
> docs: Fixed FEO name

- docs/platform_management_plan/change_management.rst
- docs/platform_management_plan/config_management.rst
- docs/platform_management_plan/documentation_management.rst
- docs/platform_management_plan/index.rst
- docs/platform_management_plan/problem_resolution.rst
- docs/platform_management_plan/quality_management.rst
- docs/platform_management_plan/release_management.rst
- docs/platform_management_plan/requirements_management.rst
- docs/platform_management_plan/risk_management.rst
- docs/platform_management_plan/safety_management.rst
- docs/platform_management_plan/software_development.rst
- docs/platform_management_plan/software_verification.rst
- docs/platform_management_plan/stakeholder_management.rst
- docs/platform_management_plan/tool_management.rst
Add initial platform management plan structure.
Issue-ref: #32
> Add initial platform management plan structure

- docs/requirements/stakeholder/index.rst
> docs: Initial version of stakeholder requirements

- docs/features/infrastructure/bazel_registry.rst
- docs/features/infrastructure/index.rst
> docs: add bazel registry entry

- docs/index.rst
- docs/platform_management_plan/project_management.rst
- docs/score_releases/index.rst
Fix link and update project lead name
Issue-ref: closes #38
> web_page: minor update of web page

- docs/features/infrastructure/bazel_registry.rst
- docs/features/integration/index.rst
Adds details about:
- module entries in registry
- module versioning and compatibility
resolves #125
> docs: registry modules

- docs/conf.py
the location was not updated in #144 which has led to #150
> docs: fix css files

- .github/CODEOWNERS
> Improvement: Update CODEOWNERS

- docs/process/guidance/contribution_request/templates/feature_request_template.rst
- docs/process/guidance/feature_flags/index.rst
- docs/process/guidance/index.rst
Adds guidance for feature flags
> Guidance: Feature Flags

- .github/workflows/docs.yml
Add missing access right to write a comment
Closes #211
> docs: Fix PR preview comment

- docs/process/guidance/contribution_request/index.rst
> docs: Improve documentation of Feature Request process closes

- docs/_tooling/extensions/score_metamodel/metamodel.py
Missing Prefix for Feature Requirements
> docs: bugfix metamodell feat req

- tools/decision_records/plantUML_draw.md
Created an ADR documenting the decision rationale for the tools used to reneder diagrams.
Fixes #183
> docs: Added decision records for PlantUML and Draw.io

- docs/_tooling/extensions/score_metamodel/metamodel.py
bugfix id convention for std req and std wp
> docs: bugfix metamodel

- docs/guidance/index.rst
- docs/guidance/publishing-gh-pages.rst
> docs: added guidance for publishing PR from forks

- index.html
Index html got deleted in the bulk clean-up
> docs: index.html got deleted

- docs/_tooling/extensions/score_metamodel/metamodel.yaml
- docs/process/guidance/general/index.rst
A naming convention for sphinx needs should be defined.
Fixes #180
> docs: create naming convention for needs

- docs/_tooling/extensions/score_metamodel/__init__.py
- docs/_tooling/extensions/score_metamodel/checks/check_options.py
- docs/_tooling/extensions/score_metamodel/checks/id_contains_feature.py
- docs/_tooling/extensions/score_metamodel/checks/standards.py
- docs/_tooling/extensions/score_metamodel/checks/traceability.py
- docs/_tooling/extensions/score_metamodel/metamodel.yaml
Added 'default-options' to yaml
Removed 'default-options' from extra_options
Added 'app' argument to checks
Removed 'needs_list_types' global
Ref: closes #396
---
The `tests` 'e.g.' "check_options_test" will be fixed in coming PR's.
> docs: Bugfix in YAML translation

- docs/platform_management_plan/safety_management.rst
> process: define safety_management plan

- docs/conf.py
- docs/index.rst
Removed logo because of trademark issue
Issue-ref: see #379
Frank Scholter Peres [frank.scholter_peres@mercedes-benz.com](mailto:frank.scholter_peres@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH
[Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)
> docs: remove logo

- docs/_tooling/extensions/score_metamodel/metamodel.yaml
- changed several attributes to optional
- corrected display of roles
fixes #335
> docs: adapt metamodel to fix warnings

- docs/process/index.rst
- docs/process/process_areas/index.rst
- docs/process/process_areas/requirements_engineering/guidance/index.rst
- docs/process/process_areas/requirements_engineering/requirements_roles.rst
- docs/process/process_areas/safety_management/guidance/index.rst
- docs/process/process_areas/safety_management/index.rst
Create TOC for Guidelines and Process Area
> docs: restructure process areas

- docs/_tooling/extensions/score_metamodel/metamodel.yaml
- docs/process/roles/index.rst
- adapt metamodel, allow satisfies for gd_req
- remove safety and security from roles
> docs: bugfix optional attributes

- docs/_tooling/conf_extras/layouts.py
- docs/_tooling/extensions/score_draw_uml_funcs/__init__.py
- docs/_tooling/extensions/score_draw_uml_funcs/helpers.py
- docs/_tooling/extensions/score_plantuml.py
- docs/_tooling/extensions/score_source_code_linker/__init__.py
- docs/_tooling/extensions/score_source_code_linker/parse_source_files.py
- docs/_tooling/extensions/score_source_code_linker/tests/test_requirement_links.py
- docs/_tooling/extensions/score_source_code_linker/tests/test_source_link.py
- docs/_tooling/incremental.py
- docs/_tooling/live_preview.py
- docs/conf.py
- tools/cr_checker/tool/cr_checker.py
- tools/dash/formatters/dash_format_converter.py
- tools/testing/pytest/main.py
- tools/testing/pytest/tests/test_rules_are_working_correctly.py
Fix all ruff & pyright warning except for those in metamodel.
related #531  (improvement ticket)
> docs: Fix ruff & pyright warnings

- .github/workflows/license_check.yml
- docs/BUILD
- tools/dash/README.md
- tools/dash/dash.bzl
- tools/dash/formatters/BUILD
- tools/dash/formatters/dash_format_converter.bzl
- tools/dash/formatters/dash_format_converter.py
- tools/testing/pytest/tests/BUILD
- tools/testing/pytest/tests/test_dash_format_converter.py
Added support for RUST dependencies check via DASH
fixes # 349
> dash: support for Rust

- .vscode/restructuredtext.code-snippets
Generated snippets via script based on current metamodel. Optional options & links not included in script.
Not yet manually verified that all snippets correct.
Ref: closes #283
> docs: Generated snippets based on Metamodel.yaml

- .github/workflows/license_check.yml
The project name is automotive.score. A wrong value was corrected via helpdesk ticket.
Fixes: #349
> dash: corrected project shortname

- docs/contribute/general/contribution_attribution.rst
- docs/contribute/general/index.rst
Wrote a small page explaining the steps needed so that your contribution gets the right attribution
Fixes: #365
> docs: contribution attribution guide

- docs/_tooling/extensions/score_layout/__init__.py
- docs/_tooling/extensions/score_layout/html_options.py
- docs/_tooling/extensions/score_layout/sphinx_options.py
- docs/conf.py
Moved to avoid sphinx/esbonio bug
Ref: closes #359
> docs: Moved layouts & html to extension

- .github/workflows/test.yml
- docs/_tooling/extensions/score_source_code_linker/__init__.py
added workflow to run the tests in the docs environment
fixes: #566
> ci: add bazel test workflow

- docs/_tooling/extensions/score_layout/__init__.py
Fixed bug in layout to fix esbonio 1.x issues
> docs: bugfix in layout for esbonio 1.x

- docs/contribute/development/development_environment.rst
Added in the dev env set-up a mention that you need to have graphviz/dot installed locally
Fixes: #415
> docs: graphviz installation note

- docs/process/process_areas/requirements_engineering/requirements_concept.rst
> process: overall versioning in requirements concept

- docs/process/process_areas/architecture_design/guidance/architecture_inspection_checklist.rst
> process: architecture_inspection_checklist - remove ASIL

- docs/_tooling/extensions/score_metamodel/metamodel.yaml
- docs/process/process_areas/architecture_design/architecture_workflow.rst
- docs/process/process_areas/architecture_design/guidance/component_architecture_template.rst
- docs/process/process_areas/architecture_design/guidance/feature_architecture_template.rst
- bugfix metamodel
- bugfix architecture guidance
> docs: bugfix optional links

- docs/process/process_areas/safety_management/guidance/template_safety_manual.rst
> docs: automated AoU list in safety_manual template

- .vscode/settings.json
- MODULE.bazel
- tools/starpls/BUILD
Add bazel LSP via bazel in vscode.
> infra: Add starpls as bazel LSP

- docs/_tooling/extensions/score_draw_uml_funcs/__init__.py
- docs/_tooling/extensions/score_draw_uml_funcs/helpers.py
- docs/_tooling/extensions/score_plantuml.py
- docs/process/process_areas/architecture_design/_assets/architecture_modeling_example.rst
- docs/process/process_areas/architecture_design/_assets/component_architecture_dynamic.puml
- docs/process/process_areas/architecture_design/architecture_concept.rst
- docs/process/process_areas/architecture_design/architecture_getstrt.rst
- docs/process/process_areas/architecture_design/guidance/index.rst
- docs/process/process_areas/architecture_design/index.rst
- remove module
- refactor feature
- refactor component
resolves #579
> docs: refactor architecture drawing extension

- docs/_tooling/extensions/score_draw_uml_funcs/helpers.py
> docs: add links architecture

- tools/cr_checker/resources/templates.ini
> cr_checker: bugfix puml

- docs/_tooling/extensions/score_metamodel/metamodel.yaml
- docs/process/process_areas/implementation/_assets/detailed_design_example.rst
- fix metamodel and the example
> doc: fix detailed design metamodel

- docs/process/process_areas/architecture_design/guidance/architecture_inspection_checklist.rst
> process: check architecture_inspection_checklist

- docs/platform_management_plan/safety_management.rst
> process: safety_management - correct reporting

- docs/process/process_areas/verification/workflows.rst
- docs/process/process_areas/verification/workproducts.rst
> process: add implementation links to verification process

- docs/platform_management_plan/safety_management.rst
- docs/process/workproducts/index.rst
> docs: remove wp duplicates

- docs/contribute/development/development_environment.rst
- docs/process/general_concepts/score_review_concept.rst
- docs/process/general_concepts/score_traceability_concept.rst
- docs/process/process_areas/architecture_design/guidance/architecture_guideline.rst
- docs/process/process_areas/implementation/implementation_getstrt.rst
- docs/process/process_areas/requirements_engineering/guidance/requirements_guideline.rst
- docs/process/process_areas/requirements_engineering/guidance/requirements_inspection_checklist.rst
- docs/process/process_areas/requirements_engineering/guidance/requirements_process_reqs.rst
- docs/process/process_areas/requirements_engineering/guidance/requirements_templates.rst
- docs/process/process_areas/requirements_engineering/requirements_concept.rst
- docs/process/process_areas/requirements_engineering/requirements_getstrt.rst
- requirements engineering
- architecture design
> docs: small process bugfixes

- docs/contribute/contribution_request/index.rst
- docs/contribute/index.rst
- docs/platform_management_plan/project_management.rst
Add a short introduction to the Contribute section of the documentation.
> docs: add introduction to Contribute section

- docs/_tooling/extensions/score_metamodel/checks/standards.py
- docs/_tooling/extensions/score_metamodel/tests/test_standards.py
- docs/process/standards/aspice_40/index.rst
- docs/process/standards/index.rst
- docs/process/standards/iso26262/iso26262.rst
- docs/process/standards/isopas8926/isopas8926.rst
- docs/process/standards/isosae21434/isosae21434.rst
- docs/process/workproducts/index.rst
- requirements and workproduct overview is available
- for every standard separately
> docs: update standard pie charts

- docs/process/process_areas/architecture_design/architecture_workproducts.rst
- docs/process/process_areas/architecture_design/guidance/architecture_guideline.rst
- docs/process/process_areas/change_management/change_management_workproducts.rst
- docs/process/process_areas/change_management/guidance/change_management_impact_analysis_template.rst
- docs/process/process_areas/requirements_engineering/guidance/requirements_guideline.rst
- docs/process/process_areas/requirements_engineering/requirements_workproducts.rst
- docs/process/process_areas/safety_management/guidance/guideline_component_classification.rst
- docs/process/process_areas/safety_management/guidance/template_module_safety_plan.rst
- docs/process/process_areas/safety_management/workproducts.rst
- docs/process/process_areas/verification/guidance/index.rst
- docs/process/process_areas/verification/guidance/verification_guideline.rst
- docs/process/process_areas/verification/workproducts.rst
- docs/process/workproducts/index.rst
> doc: include isopas wp and req

- docs/platform_management_plan/safety_management.rst
- docs/process/process_areas/safety_management/workflows.rst
- docs/process/standards/index.rst
- docs/process/workflows/process_management.rst
> doc: tailored wp linkage

- docs/contribute/development/python/coding_guidelines.rst
- pyproject.toml
see changes in rst
rendered page at https://eclipse-score.github.io/score/pr-840/contribute/development/python/coding_guidelines.html
> python: enhance Python coding guidelines with type annotation recommendations

- docs/platform_management_plan/software_verification.rst
> process: add testing independence to verification plan

- docs/platform_management_plan/software_verification.rst
- docs/process/process_areas/verification/guidance/verification_process_toolreqs.rst
- docs/process/process_areas/verification/verification_concept.rst
- docs/process/process_areas/verification/workproducts.rst
Implements a finding from the 3rd interim audit.
closes #791
> process: adjust test levels and methods

- .github/actions/gitlint/action.yml
- .gitlint
Use correct link to docs in gitlint error message.
> git: Update gitlint error message

- docs/process/standards/isosae21434/isosae21434.rst
> process: improve sub-clause references for isosae21434

- docs/platform_management_plan/safety_management.rst
- docs/platform_management_plan/software_verification.rst
- docs/process/general_concepts/score_review_concept.rst
- docs/process/process_areas/architecture_design/architecture_workflow.rst
- docs/process/process_areas/architecture_design/architecture_workproducts.rst
- docs/process/process_areas/architecture_design/guidance/architecture_process_reqs.rst
- docs/process/process_areas/architecture_design/index.rst
- docs/process/process_areas/documentation_management/index.rst
- docs/process/process_areas/safety_management/index.rst
- docs/process/workproducts/index.rst
> doc: improvements on wp tags and docu

- BUILD
- MODULE.bazel
added score_ prefix for consistency
Addresses: #922
> dash: rename for consistency

- docs/_tooling/extensions/score_metamodel/__init__.py
- docs/_tooling/extensions/score_metamodel/tests/rst/attributes/test_attributes_format_description.rst
- docs/_tooling/extensions/score_metamodel/tests/rst/attributes/test_attributes_format_id_format.rst
- docs/_tooling/extensions/score_metamodel/tests/rst/attributes/test_attributes_format_id_length.rst
- docs/_tooling/extensions/score_metamodel/tests/rst/attributes/test_attributes_format_title.rst
- docs/_tooling/extensions/score_metamodel/tests/rst/graph/test_metamodel_graph.rst
- docs/_tooling/extensions/score_metamodel/tests/rst/id_contains_feature/test_id_contains_feature.rst
- docs/_tooling/extensions/score_metamodel/tests/rst/options/test_options_extra_option.rst
- docs/_tooling/extensions/score_metamodel/tests/rst/options/test_options_options.rst
- docs/_tooling/extensions/score_metamodel/tests/test_rules_file_based.py
Add new test files
Comment test files
Optimize check of enabled checks
> tooling: Add new test files for check rule tests

- docs/_tooling/extensions/score_metamodel/__init__.py
- docs/conf.py
docs:incremental reports lots of warnings on main branch
> fix: docs:incremental reports lots of warnings on main branch

- docs/process/process_areas/change_management/guidance/change_management_component_template.rst
- docs/process/process_areas/change_management/guidance/change_management_feature_template.rst
- docs/process/process_areas/documentation_management/documentation_concept.rst
- docs/process/process_areas/documentation_management/guidance/documentation_checklist.rst
- docs/process/process_areas/documentation_management/guidance/documentation_guideline.rst
> docs: typos correction in doc mgt process

- docs/platform_management_plan/config_management.rst
- docs/process/process_areas/configuration_management/guidance/process_req.rst
- docs/process/process_areas/release_management/guidance/release_templates.rst
> docs: update config_management with links

- docs/process/process_areas/release_management/guidance/release_guideline.rst
- docs/process/process_areas/release_management/release_concept.rst
- docs/process/process_areas/release_management/release_roles.rst
- docs/process/process_areas/release_management/release_workflow.rst
> docs: release process small bugfixes

- docs/contribute/contribution_request/index.rst
- docs/features/communication/ipc/architecture/feature_architecture.rst
- docs/features/communication/ipc/index.rst
- docs/features/communication/ipc/requirements/index.rst
- docs/features/communication/ipc/safety_planning/index.rst
- docs/platform_management_plan/safety_management.rst
> docs: update platform safety plan with v0.5 features

- .github/workflows/docs.yml
Variable name change was missed.
> Bugfix: Namechange

- .github/workflows/docs-cleanup.yml
And added permissions to create labels.
Related: https://github.com/eclipse-score/score/issues/1029
> infra: Fix auto-close PR limit

- docs/features/frameworks/feo/modules/feo/docs/manual/safety_manual.rst
- docs/features/frameworks/feo/modules/feo/feo/docs/index.rst
- docs/features/frameworks/feo/modules/feo/feo/docs/requirements/component_requirements.rst
- docs/features/frameworks/feo/modules/feo/feo_com/docs/index.rst
- docs/features/frameworks/feo/modules/feo/feo_log/docs/index.rst
- docs/features/frameworks/feo/modules/feo/feo_time/docs/index.rst
- docs/features/frameworks/feo/modules/feo/feo_tracing/docs/index.rst
> Added FEO component requirements

- docs/features/time/_assets/timesync-chain.drawio.svg
- docs/features/time/_assets/timesync-external.drawio.svg
- docs/features/time/_assets/timesync-vehicle.drawio.svg
- docs/features/time/index.rst
> updated motivation

- docs/platform_management_plan/config_management.rst
- docs/platform_management_plan/project_management.rst
> Fix CfgMgt Plan audit actions

- docs/features/communication/abi_compatible_data_types/index.rst
Some comments on reflectivity and inline type descriptions for ABI compatible types, plus alternative solutions.
> docs: reflection in ABI compatible types

- docs/platform_management_plan/config_management.rst
> Align config-mgt-plan with process updates

- docs/features/frameworks/feo/modules/feo/feo/docs/architecture/_assets/act_chain.puml
- docs/features/frameworks/feo/modules/feo/feo/docs/architecture/_assets/dyn_arch.puml
- docs/features/frameworks/feo/modules/feo/feo/docs/architecture/_assets/stat_arch.puml
- docs/features/frameworks/feo/modules/feo/feo/docs/architecture/component_architecture.rst
> Adding FEO component architecture

- docs/contribute/general/release_guide.rst
- docs/platform_management_plan/release_management.rst
> Module release guide align with PMP

- docs/features/frameworks/feo/index.rst
- docs/features/frameworks/feo/modules/feo/feo/docs/requirements/component_requirements.rst
- docs/features/frameworks/feo/requirements/index.rst
> FEO feature request and requirements: Add error handling according to #944

- MODULE.bazel
- README.md
- docs/contribute/general/folder.rst
- docs/features/communication/ipc/docs/safety_planning/index.rst
- docs/platform_management_plan/quality_management.rst
- docs/platform_management_plan/safety_management.rst
- docs/platform_management_plan/software_verification.rst
Recent upgrade was missing a commit with RST changes => here included. 
Changed the README to reflect new commands.
Updated versions to prepare for new release.
> Fixing rst errors & Upgrading README & version

- MODULE.bazel
The versioning of the Module needs to be the same as the release .
We currently have only released version 0.2 therefore next release (non breaking in content) should be 0.3 =>
> Fix versioning

- docs/features/frameworks/feo/safety_planning/index.rst
> Add issues to the FEO feature safety plan

- MODULE.bazel
downgrade aspect_rules_py to version 1.4.0 to solve consumer_test in docs-as-code
fix: https://github.com/eclipse-score/docs-as-code/issues/166
> downgrade aspect_rules_py to version 1.4.0

- docs/features/communication/abi_compatible_data_types/index.rst
- docs/features/communication/abi_compatible_data_types/requirements.rst
- docs/features/communication/index.rst
- docs/requirements/stakeholder/index.rst
> abi compatible data types feature request

- docs/platform_management_plan/project_management.rst
Removed line as discussed in https://github.com/eclipse-score/score/issues/1623
Frank Scholter Peres <frank.scholter_peres@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH
[Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)
> fix: #1623 removed line of the election

- .github/CODEOWNERS
CODEOWNERS needed these updates:
- PMP responsibles are the TLs but the approval needs to be done by the process team to make sure its conform to our process_description
- Rebekka and Max left S-CORE and Volker was elected as committer
> CODEOWNERS - correct and update

- docs/contribute/fork/index.md
- docs/contribute/index.rst
Add an "Enterprise Forking Guide for S-CORE Repositories"
Content is up to lots of discussions :-)
> add forking guide

- MODULE.bazel
- docs/platform_management_plan/documentation_management.rst
- docs/platform_management_plan/safety_management.rst
Update the Documentation Management Plan. The plan is now structured according the folder structure. All features, modules and components are included. Missing documents for features, modules and components were shown as entries of the expected template. All lists can be referred from other plans to reduce the maintenance effort.
The Safety Management Plan is also updated to this aspect.
> Documentation Management - Update Documentation Management Plan

- docs/platform_management_plan/project_management.rst
To simplify the planning and collaboration process within the S-CORE contribution community, it is essential to define and align on the types of work items, their meanings, and the interactions between them.
This Pull Request aims to establish a clear and agreed-upon structure for work item types within the TL circle. The goal is to reach a common understanding and eventually roll out the defined model across the community.
> rework the section of work item types and relationship of the same
