- docs/_assets/css/score.css
- docs/conf.py
The width of the content gets increased.
The left sidebar does not show a scrollbar anymore if the documentation tree fits in the available space.
Issue-ref: fix #51
> docs: content width and hide scrolbar (#2)

- docs/_assets/css/score.css
The horizontal scrollbar gets hidden for the left navigation.
Contains also a small fix for the sidebar width for smartphone/small screens.
Issue-ref: fixes #60
> docs: Fix of scrollbar

- docs/features/analysis-infra/index.rst
- docs/features/analysis-infra/logging/console-output/index.rst
- docs/features/analysis-infra/logging/index.rst
- docs/features/analysis-infra/logging/mw-log-api/index.rst
- docs/features/communication/index.rst
- docs/features/communication/ipc/index.rst
- docs/features/frameworks/fixed-order-execution/index.rst
- docs/features/frameworks/index.rst
- docs/features/persistency/file-access/index.rst
- docs/features/persistency/index.rst
- docs/features/persistency/key-value-storage/index.rst
> Add MVP features

- docs/platform_management_plan/project_management.rst
- docs/score_releases/index.rst
> Add links to GitHub discussions in the project management plan

- docs/process/guidelines/contribution_request/index.rst
- docs/process/guidelines/templates/feature_request_template.rst
- docs/process/guidelines/templates/index.rst
> Add feature request template

- .vscode/settings.json
Currently "mandatory wrapping" is configured in the project settings, which is not what everyone wants.
Example: It took me a surprisingly long amount of time to understand a line of code, because it looked like two lines. I've not used wrapping in the last 10 years... or ever.
At the same time let's add a python ruler for 80 characters, since it's the de-facto-standard. Not only de-facto, it is the standard. See PEP-8.
> Improve line length settings

- .gitlint
- docs/process/guidance/git/index.rst
Commits are linked by Github to the PR that introduced them. It is impossible to merge a commit without PR.
Hence, it is sufficient if the PR links to issues.
We have no tooling that would verify that the linkage of a commit is correct. Thus, making an issue reference in the commit message mandatory holds no benefit.
It is still allowed to reference an issue in a commit message. It is simply no longer mandatory.
Issue-ref: see #131
Issue-ref: closes #119
> Lift requirement for Issue-Ref in commit message

- .vscode/extensions.json
This adds drawio, rst and esbonio extensions. As those three are quite typically useful when editing documentation.
> docs: add recommended extensions

- .gitlint
The documentation of enabled/disabled rules was a little off. And I was wondering why a body is required, until I found the commit message guidelines, so it seems to make sense to add that link.
> git: update gitlint documentation

- .github/actions/deploy-versioned-pages/action.yml
- .github/workflows/docs-cleanup.yml
- .github/workflows/docs.yml
Documentation is built during PRs, and currently, an artifact is uploaded, with a link to the artifact added to the PR. However, this generates numerous links (e.g., see #94), and to view the documentation, users must download and extract the artifact manually.
Provide a direct link to the documentation preview in PRs. This link should allow users to preview the documentation directly, without extra steps, and remain stable throughout the PR's lifetime, unaffected by new commits.
Since GitHub Pages supports only a single folder or artifact per repository, and rebuilding all versions of documentation for every PR is inefficient, a new approach is needed. The gh-pages branch will act as persistent storage for documentation artifacts. Each PR will store its specific documentation in a …
> docs: preview in PRs

- .github/workflows/docs.yml
And use correct artefact name when deploying (fallback step).
> docs: upload always

- .github/actions/deploy-versioned-pages/action.yml
- .yamlfmt
Allow line breaks by adding  a yamlfmt config file. Made action.yaml more readable.
closes [#127 ] (improvement ticket)
> allow empty lines on github workflows

- .devcontainer/README.md
- .devcontainer/devcontainer.json
- .vscode/extensions.json
- docs/BUILD
- docs/_tooling/sphinx_extensions/BUILD
As described in the linked issue, this switches py_binary and py_library to aspect_rules_py. This way there is no dependency to the system python executable.
closes #178
> IDE: Support Codespaces

- .github/actions/gitlint/action.yml
Gitlint action will provide information on how to use git to solve commit message warnings.
related [#210 ] (improvement ticket)
> gitlint: Add git hints for gitlint warnings

- docs/_tooling/sphinx_extensions/sphinx_extensions/check_options.py
- docs/_tooling/sphinx_extensions/sphinx_extensions/checks.py
- docs/_tooling/sphinx_extensions/test/check_options_test.py
In this PR we completed part 1 from this task https://github.com/eclipse-score/score/issues/204
We added checks for optional options.
We also checked all mandatory options for every type of need which are normally requirement options plus optional options plus some list of default options that usually exist in need as well as we adapted the tests for each of them
> Aymen soussi 01 adapt checks

- .github/actions/deploy-versioned-pages/action.yml
- .github/workflows/docs-cleanup.yml
- docs/_tooling/assets/css/score.css
- docs/conf.py
Use current theme(pydata_sphinx_theme) [version switcher dropdown](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html#) to display a version selector. Because the switcher requires a json, the versions file is parsed into versions.json. 
Also a css update of the version switcher is required to proper display(vertical scrollbar) the list of versions.
Because of a current bug #194 this PR will not show the docs preview. However I created another PR for preview only: https://nicu1989.github.io/score/pr-7/
Here is also a picture of the dropdown:
Also there is a way to view the versions file in browser using the json file: https://eclipse-score.github.io/score/versions.json
closes [#250 ] (improvement ticket)
> docs: Add version switcher

- tools/cr_checker/cr_checker.bzl
- tools/cr_checker/tool/README.md
- tools/cr_checker/tool/cr_checker.py
The new option enables the removal of outdated copyright headers from source files. This functionality is potentially destructive and should be used with extreme caution.
> cr_checker: Add `remove offset` option

- docs/features/communication/ipc/index.rst
- docs/features/communication/ipc/requirements/index.rst
Provides a proposal for a communication framework feature.
Note:
Only the second commit is actually relevant. The first commit is only to provide the means to put requirements.
> Feature request: IPC Framework

- docs/_tooling/extensions/score_plantuml.py
If a plantuml figure cannot be rendered an error image containing the error message will be displayed
> Enable Plantuml syntax error image

- docs/conf.py
Remove title(since its replaced by logo) and re-added missing theme switcher(dark/light mode).
closes [#325 ] (bugfix ticket)
> docs: Fix documentation header display

- .github/actions/deploy-versioned-pages/action.yml
- .github/workflows/docs-cleanup.yml
- .github/workflows/docs.yml
Fixes issues with race conditions by enabling folder cleaning 
Requires maintainer approval via an environment.
Adapt workflows to correctly handle pull_request_target by explicitly checking out the correct repository.
Flattened folder structure
gh-pages/
.................
│─ pr-42/         # PR #42 preview
│─ pr-99/         # PR #99 preview
│─ feature-x/     # Feature branch preview
│─ v17/           # Tagged release
│─ main/          # main branch (alternatively "latest")
In addition to this repo, there are a couple more changes that are needed:
- the **otterdog** repo has to be updated and add the proper maintainers to the github-pages env
- the **eclipse-score.github.io** repo has to be updated so that the Docs URL  references the /main folder by default
closes #168 #194 #269
> docs: allow publishing docs from forked PRs

- .github/workflows/docs-cleanup.yml
The target for GH Pages can be left to `pull_request`, because only the gh-pages from the branch repo are modified.
Still, there was always a problem with pushing to the gh-pages.
Modified the permissions.
Fixes: #194
> docs: clean-up bug

- .github/workflows/docs-cleanup.yml
docs: changed action for pushing to gh-pages
Swtiched to another action which we use for publishing PR previews
Fixes https://github.com/eclipse-score/score/issues/355
> docs: switched action 

- tools/cr_checker/tool/cr_checker.py
This commit fix the issue when user wants to filter BUILD files using `--extentions`. The files are now collected by tool.
resolves #324
> cr_checker: Fix extention option for BUILD files

- docs/_tooling/extensions/score_metamodel/__init__.py
- docs/_tooling/extensions/score_metamodel/metamodel.yaml
In order to keep the intial metamodel structure identic with former
python file, the rename of id and status will be done during parsing.
closes #286 (improvement ticket)
> docs: Fix metamodel.yaml id and status tags

- .github/actions/deploy-versioned-pages/action.yml
Every commit on a PR will trigger CI step to post the same comment.
Now only the initial PR comment will be posted.
**Note:** When triggering a workflow by pull_request_target the workflow that runs is the one from the target branch of the PR.
This means that until this PR is merged the comment will be published multiple times(as it currently does) including for this PR.
There is a github community discussion here: https://github.com/orgs/community/discussions/25437 
closes #391
> ci: Fix multiple PR comments with docs link

- .bazelrc
- .github/workflows/license_check.yml
- MODULE.bazel
- docs/BUILD
- tools/dash/dash.bzl
- tools/dash/formatters/BUILD
- tools/dash/formatters/dash_format_converter.bzl
- tools/dash/formatters/dash_format_converter.py
picked-up PR#155
This PR adds support for the DASH tool within the S-CORE Bazel build system. The integration includes:
Defining custom Bazel rules to handle the DASH tool's setup and execution.
Adding necessary dependencies in BUILD files to ensure compatibility with existing project requirements.
Validating the integration with the current CI pipeline to maintain a seamless build and deployment process.
This enhancement simplifies the workflow by consolidating tools into the Bazel build system, improving build automation and traceability.
The license check preparation workflow - which basically executed dash within bazel
won't stop on failure.
It will display the outcome to the PR in form of a comment
Fixes https://github.com/eclipse-score/score/issues/347 …
> dash: integration 

- docs/_tooling/extensions/score_metamodel/checks/check_options.py
- docs/_tooling/extensions/score_metamodel/checks/id_format_and_length.py
- docs/_tooling/extensions/score_metamodel/checks/standards.py
Added the 'app' argument to missing checks.
Disabled two checks which aren't possible to be fulfilled at the moment. 
Reverted deletion of ignoring '..._back' options
Ref: closes #419
> docs: Add 'app' to checks, and disabled two.

- docs/_tooling/extensions/score_metamodel/checks/id_format_and_length.py
- docs/_tooling/extensions/score_metamodel/checks/traceability.py
- docs/_tooling/extensions/score_metamodel/tests/test_id_format_and_length.py
- docs/features/communication/ipc/index.rst
- docs/features/communication/ipc/requirements/index.rst
- docs/process/guidance/contribution_request/index.rst
- docs/process/guidance/contribution_request/templates/feature_request_template.rst
- docs/process/guidance/requirements/requirement_template.rst
- docs/process/workflows/architecture_design.rst
- docs/process/workflows/change_management.rst
- docs/process/workflows/platform_management.rst
- docs/process/workflows/process_management.rst
- docs/process/workflows/quality_management.rst
- docs/process/workflows/requirements_management.rst
- docs/process/workflows/safety_analysis.rst
- docs/process/workproducts/index.rst
- docs/requirements/stakeholder/index.rst
- docs/requirements/tool/index.rst
Replace all ids and options items by their value in small letters.
I used 2 regex to do the job (:[a-z]*: .*__.*) and (:[a-z]*: .*_.*)  and replaced them with \L$1 all using VS Code option to search and replace regex patterns to handle all options and id cases that not follow the pattern.
In another PR we will handle the case of id and options that start only with one "_" Plus there were some small mistakes like changing ASIL_D/B to asil_d/b and some small unnecessary ones that I fixed manually by returning them to their old value.
Related to: #282
> tooling: Correct upper case values in docs build errors.

- BUILD
- docs/BUILD
- tools/dash/README.md
- tools/dash/dash.bzl
The README.md provides better insignt how Bazel and Dash (EF License checker) communicate and work in chain. Also the target for checking Python licenses is moved to docs directory.
> dash: Add README.md and move target to docs directory

- tools/decision_records/python_tooling.md
Decision record to clarify & write down decisions and results of discussions made in slack voting & meetings regarding python tooling. 
Feedback on wording, missing reasons for inclusions  & exclusions and content are welcome.
> docs: Added decision records for python tooling

- .github/workflows/docs.yml
Removed building docs from feature branches in CI. Docs are only build for main branch and PRs.
closes [#412] (bugfix ticket)
> docs: Build docs only for main branch and PRs

- docs/_tooling/conf_extras/layouts.py
> docs: hide safety and security if empty

- docs/_tooling/extensions/score_metamodel/checks/id_contains_feature.py
- docs/_tooling/extensions/score_metamodel/checks/id_format_and_length.py
- docs/_tooling/extensions/score_metamodel/checks/traceability.py
- docs/_tooling/extensions/score_metamodel/tests/test_traceability.py
- docs/features/communication/ipc/index.rst
- docs/features/communication/ipc/requirements/index.rst
- docs/requirements/stakeholder/index.rst
- docs/requirements/tool/index.rst
Replace all IDs of stakeholders requirements that include numbers with meaningful IDs.
Related to: #282
> tooling: Correct Stakeholders' requirements ids to be meaningful.

- .github/workflows/license_check.yml
- docs/BUILD
- tools/dash/README.md
- tools/dash/dash.bzl
Enabled the execution of `review` for the dash tool in the CI pipeline. This won't work on local development unless developers have their own DASH PATs. Important notice:  secrets remain in the CI workflow, not in Bazel BUILD files, they won't be exposed.
Fixes: #348
> dash: enable automatic license clearance via review action

- .github/workflows/license_check.yml
It appears there are some issues with the call
```
INFO: Running command line: bazel-bin/docs/license.check.python docs/formatted.txt -review -project eclipse-score.score -repo https://github.com/eclipse-score/score.git -token ***
Exception in thread "main" java.lang.RuntimeException: org.eclipse.dash.api.EclipseApi: An error occurred while calling the API.
at org.eclipse.dash.api.EclipseApi.getApiData(EclipseApi.java:174)
at org.eclipse.dash.api.EclipseApi.getProject(EclipseApi.java:127)
at org.eclipse.dash.licenses.validation.EclipseProjectIdValidator.validate(EclipseProjectIdValidator.java:31)
at org.eclipse.dash.licenses.cli.Main.main(Main.java:78)
```
Tried looking into the code and this is the line failing:
```java
if (result == 400 || result == 404) {
// FIXME As of December 2024, …
```
> dash: issue calling DASH API

- .github/workflows/license_check.yml
Update comment if it already exists instead of spamming.
Note: When triggering a workflow by pull_request_target the workflow that runs is the one from the target branch of the PR.
This means that until this PR is merged the comment will be published multiple times(as it currently does) including for this PR.
related #349  (improvement ticket)
> dash: Update license check comment

- docs/_tooling/extensions/score_draw_uml_funcs/__init__.py
- docs/_tooling/extensions/score_plantuml.py
- docs/_tooling/extensions/score_source_code_linker/__init__.py
- docs/_tooling/extensions/score_source_code_linker/tests/test_requirement_links.py
- docs/_tooling/extensions/score_source_code_linker/tests/test_source_link.py
- docs/_tooling/live_preview.py
- tools/testing/pytest/main.py
Remove sphinx & pytest `# type: ignore `suppresions. These were wrongfully added.
Selecting the right interpreter fixes the warnings instead.
related #531  (improvement ticket)
> docs: Remove ruff&pyright current suppresions

- .clwb/.idea/.gitignore
This directory is created by the bazel plugin, and should not persist over different users.
> ide: Ignore CLion IDE Aspect directory

- docs/platform_management_plan/change_management.rst
- docs/process/process_areas/change_management/change_management_concept.rst
- docs/process/process_areas/change_management/change_management_workproducts.rst
- docs/process/process_areas/change_management/guidance/change_management_checklist.rst
- docs/process/process_areas/change_management/guidance/change_management_component_template.rst
- docs/process/process_areas/change_management/guidance/change_management_feature_template.rst
- docs/process/process_areas/change_management/guidance/change_management_guideline.rst
- docs/process/process_areas/change_management/guidance/change_management_impact_analysis_template.rst
- docs/process/process_areas/change_management/guidance/change_management_reqs.rst
Impact Analysis Template modified
Template shall be copied to Issue for planning
Resolves: #621
> process: improve impact analysis

- docs/BUILD
- docs/process/process_areas/implementation/guidance/cpp/code_analysis.rst
- docs/process/process_areas/implementation/guidance/cpp/coding_guidelines.rst
- docs/process/process_areas/implementation/guidance/cpp/index.rst
- docs/process/process_areas/implementation/guidance/cpp/misra_2023_rule_mapping.rst
- docs/process/process_areas/implementation/guidance/index.rst
- docs/process/process_areas/implementation/index.rst
- Coding Guidelines
- Code Analysis
resolves #529
> impl: proposal for coding guidelines

- docs/_tooling/extensions/score_source_code_linker/collect_source_files.bzl
New feature: it can now also handle filegroups as an input, as it no longer assumes every rule has a "deps" attribute.
Otherwise it's only refactoring.
> docs: refactor collect_source_files.bzl

- docs/_tooling/extensions/score_metamodel/__init__.py
- docs/_tooling/extensions/score_metamodel/log.py
- docs/_tooling/extensions/score_metamodel/tests/__init__.py
Esbonio warnings have correct file path while keeping a correct file path for bazel build and run.
closes [#174] (bugfix ticket)
> docs: Fix warnings via esbonio

- docs/_tooling/extensions/score_metamodel/checks/traceability.py
- docs/_tooling/extensions/score_metamodel/tests/test_traceability.py
Traceability checks being disabled
The checks will be moved to the metamodel graph checks in a future PR.
> docs: Disabling 'traceability-checks.

- docs/_tooling/extensions/score_metamodel/__init__.py
- docs/_tooling/extensions/score_metamodel/checks/attributes_format.py
- docs/_tooling/extensions/score_metamodel/checks/check_options.py
- docs/_tooling/extensions/score_metamodel/checks/standards.py
- docs/_tooling/extensions/score_metamodel/metamodel.yaml
- docs/_tooling/extensions/score_metamodel/tests/test_attributes_format.py
- docs/_tooling/extensions/score_metamodel/tests/test_check_options.py
- docs/_tooling/extensions/score_metamodel/tests/test_id_contains_feature.py
- docs/_tooling/extensions/score_metamodel/tests/test_standards.py
- docs/_tooling/extensions/score_source_code_linker/__init__.py
Link existing checks via source code linker and implement missing checks.
We decided to disable the optional_links check for now and correct the finding related to that in a separate PR 
closes #521
> tooling: Link and create checks for guidance process requirements

- docs/BUILD
Enabled source_code_linker to parse all files in metamodel instead of just python files.
> docs: Expandedmissing source_code_linker parsing

- docs/_tooling/extensions/score_metamodel/__init__.py
- docs/_tooling/extensions/score_metamodel/checks/attributes_format.py
- docs/_tooling/extensions/score_metamodel/checks/check_options.py
- docs/_tooling/extensions/score_metamodel/checks/graph_checks.py
- docs/_tooling/extensions/score_metamodel/checks/standards.py
- docs/_tooling/extensions/score_metamodel/checks/traceability.py
- docs/_tooling/extensions/score_metamodel/log.py
- docs/_tooling/extensions/score_metamodel/tests/__init__.py
- docs/_tooling/extensions/score_metamodel/tests/test_attributes_format.py
- docs/_tooling/extensions/score_metamodel/tests/test_standards.py
- docs/_tooling/extensions/score_metamodel/tests/test_traceability.py
- docs/_tooling/extensions/score_source_code_linker/__init__.py
Fix ruff and pylance errors in the score_metamode folder.
Related to. #531
> tooling: Correct Ruff and Pylance error

- docs/contribute/general/git.rst
It is practice to do squash commits, but this may not be always possible.
This commit adds a draft for the rules concluded in #406.
> docs: redefine how-to merge pull request

- docs/process/process_areas/verification/verification_roles.rst
- docs/process/process_areas/verification/workflows.rst
- docs/process/roles/index.rst
During the 3rd interim audit, the demand was formulated, that we need to have a verification specific role, which could be filled by the existing testing community. This is added by this PR.
closes: Improvement: Testing Community Role #777
> process: add testing community role

- docs/_tooling/extensions/score_source_code_linker/__init__.py
- docs/_tooling/extensions/score_source_code_linker/tests/test_source_link.py
- docs/_tooling/incremental.py
Fix pyright errors in _tooling and score_source_code_linker by suppressing type errors in the code.
Fixes: https://github.com/eclipse-score/score/issues/531
> tooling: Fix pyright errors in tooling

- docs/conf.py
Esbonio failed due to the same option being registered twice.
Fixed with deletion one of one register.
> fix: Esbonio bugfix in header service

- .vscode/extensions.json
- .vscode/settings.json
After reviewing the `process `documentation it seems that there are a lot of spell mistakes so I added the VSCode extension for rst spell checking.
related #544   (improvement ticket)
> docs: Add vscode spell check extension

- .github/workflows/license_check.yml
Even if ECLIPSE_GITLAB_API_TOKEN is set as an organization secret, it won’t be automatically available inside a reusable workflow. Reusable workflows are not automatically given access to secrets from the caller's context ( not even org secrets).
Addresses: #813
> cicd: bugfix

- docs/platform_management_plan/config_management.rst
- docs/process/process_areas/configuration_management/guidance/process_req.rst
- docs/process/process_areas/configuration_management/index.rst
- docs/process/process_areas/index.rst
> doc: initial config mgt process

- docs/BUILD
- docs/_tooling/docs.bzl
- docs/_tooling/extensions/score_metamodel/tests/rst/attributes/test_attributes_format_description.rst
- docs/_tooling/extensions/score_metamodel/tests/rst/attributes/test_attributes_format_id_format.rst
- docs/_tooling/extensions/score_metamodel/tests/rst/attributes/test_attributes_format_id_length.rst
- docs/_tooling/extensions/score_metamodel/tests/rst/attributes/test_attributes_format_title.rst
- docs/_tooling/extensions/score_metamodel/tests/rst/graph/test_metamodel_graph.rst
- docs/_tooling/extensions/score_metamodel/tests/rst/options/test_options_extra_option.rst
- docs/_tooling/extensions/score_metamodel/tests/rst/options/test_options_options.rst
- docs/_tooling/extensions/score_metamodel/tests/rst/test_asil.rst
- docs/_tooling/extensions/score_metamodel/tests/test_rules_file_based.py
Introduce new testing method with rst files as input.
Fixes: https://github.com/eclipse-score/score/issues/736
> tooling: Add file based rule check tests

- docs/_tooling/extensions/score_metamodel/tests/README.md
- docs/_tooling/extensions/score_metamodel/tests/test_rules_file_based.py
Add documentation for the file based rule checks.
Test function checks file name and line number
separately from warning message now.
Fixes: https://github.com/eclipse-score/score/issues/736
> tooling: Add docu and change matching function

- docs/_tooling/extensions/score_draw_uml_funcs/__init__.py
- docs/_tooling/extensions/score_draw_uml_funcs/helpers.py
- docs/_tooling/extensions/score_header_service/header_service.py
- docs/_tooling/extensions/score_header_service/test/test_header_service.py
- docs/_tooling/extensions/score_layout/sphinx_options.py
- docs/_tooling/extensions/score_metamodel/__init__.py
- docs/_tooling/extensions/score_metamodel/checks/check_options.py
- docs/_tooling/extensions/score_metamodel/tests/test_attributes_format.py
- docs/_tooling/extensions/score_metamodel/tests/test_check_options.py
- docs/_tooling/extensions/score_metamodel/tests/test_standards.py
- docs/_tooling/extensions/score_source_code_linker/parse_source_files.py
Fix most of the Pylance warnings for reportUnknownVariableType except those related to the Metamodel complex data type.
I also divided some complex functions into small ones to reduce the complexity.
As well I didn't fix the new warnings coming from the new way of testing from the main as they are out of context of this PR.
I just skipped 26 warnings related to loading the metamodel, as the type is very complex. Plus, there is one extra sphinx_autobuild function import warning that has an unknown type.
Maybe someone from the reviewers can give an opinion on this complex data, or we could ignore it for now.
Related to: #836
> tooling: Reduce most of Pylance remaining new types of warnings

- docs/_tooling/extensions/score_metamodel/__init__.py
- docs/_tooling/extensions/score_metamodel/log.py
- docs/_tooling/extensions/score_metamodel/tests/__init__.py
Implement a new function that logs errors related to new checks as Info's and not normal warnings, with a message requesting to fix them before the new project version release.
A request for all team members to understand the new implementation of the log function and use it correctly whenever you introduce new checks in the project  
close: #735
> tooling: Log errors related to new checks as Infos

- MODULE.bazel
- README.md
Enable Python coverage in MODULE.bazel
Document how to generate coverage reports
Fixes: https://github.com/eclipse-score/tooling/issues/23
> tooling: Enable and document Python coverage

- docs/platform_management_plan/tool_management.rst
Two overlapping merges conflicts in workflow definition, this bugfixes resolves the topic
> bugfix: correct needs link to workflow to enable documentation build

- MODULE.bazel
* quick fix for randomly failing build by @AlexanderLanin in https://github.com/eclipse-score/docs-as-code/pull/13
* fix command line argument for live_preview by @AlexanderLanin in https://github.com/eclipse-score/docs-as-code/pull/15
* rename process-docs to examples/simple by @AlexanderLanin in https://github.com/eclipse-score/docs-as-code/pull/17
**Full Changelog**: https://github.com/eclipse-score/docs-as-code/compare/release-0.1.1...release-0.2.0
> chore: update score_docs_as_code to 0.2.0

- docs/contribute/contribution_request/index.rst
- docs/contribute/index.rst
- docs/platform_management_plan/problem_resolution.rst
- docs/platform_management_plan/project_management.rst
- docs/process/process_areas/release_management/guidance/release_guideline.rst
- docs/process/roles/index.rst
- docs/score_releases/index.rst
Rename cross-functional teams to feature teams and update the links.
> rename cft to ft

- .github/workflows/docs.yml
- MODULE.bazel
- docs/BUILD
Changing docs-as-code to new version.
In conjunction with that, changing the GH-Workflow to reflect new naming.
Removing duplicate targets that have been moved to 'docs-as-code'
> Preparing for first pre-release

- .github/workflows/docs.yml
This should fix the need to add '/html' to the end of URL's in order to get to the Documentation correctly.
> Fix documentation deployment

- .github/workflows/docs-cleanup.yml
Close PRs older than 30 days.
Related: https://github.com/eclipse-score/score/issues/1029
> infra: Autoclose stale PRs

- MODULE.bazel
- docs/conf.py
Currently all needs that are external (like process) will be filtered out in the 'needs.json'. 
This allows the needs.json to contain ALL of the needs imported. 
In a future PR the filter can probably be adapted to make it more efficent, e.g. only get external needs that are actually needed. 
~~## ⚠️  This PR should not be merged until new docs-as-code is out. As that has bugfixes that might be imported for here.~~
New docs-as-code version is available. PR can be reviewed and mered. 
--- 
I pulled the version to a new major one, as the change in needs.json is something that changes how it could be used.
I think that makes sense (at least in my head) .
> Enable external needs json & increase versions

- MODULE.bazel
- docs/platform_management_plan/safety_management.rst
> update process_description version

- .github/workflows/docs-cleanup.yml
Close stale PR that have a specific feature request labeled after 90+10 days.
Closes: https://github.com/eclipse-score/score/issues/1235
> infra: Handle stale feature_request PR

- docs/contribute/development/rust/index.rst
- docs/contribute/development/rust/rust_api_design.rst
Add a chapter about how to design public APIs in Rust for S-CORE. The first bit explains how to create mockable APIs by means of trais and how to use them on user side.
Closes https://github.com/eclipse-score/score/issues/1265
> Start writing Rust API guidelines for S-CORE

- docs/features/communication/abi_compatible_data_types/index.rst
- docs/features/communication/abi_compatible_data_types/requirements.rst
- added Variant data type
- added Queue data type
- removed reflection from version 1.0
- removed restriction on equality of architecture
- made internal fields on ABI types private
> Implemented changes as discussed on 2025-07-18

- docs/features/persistency/kvs/requirements/index.rst
- docs/modules/persistency/kvs/docs/requirements/index.rst
Persistency tags to be added only to needs from persistency/kvs/requirements.
Related: https://github.com/eclipse-score/score/issues/1597
> docs: Fix persistency tags

- docs/features/baselibs/docs/requirements/index.rst
- docs/modules/baselibs/result/docs/index.rst
- docs/modules/baselibs/result/docs/requirements.rst
Add requirements for the result library.
> docs: add Result Library requirements

- .devcontainer/alt_container_docker_on_windows/devcontainer.json
- .devcontainer/devcontainer.json
- .devcontainer/initialize_command
- .devcontainer/initialize_command.cmd
- docs/contribute/development/development_environment.rst
Linux / WSL and Docker on Windows use different scripting languages and this shows in the initializeCommand. With this solution the same devcontainer.json file can be used on all platforms, which reduces maintenance costs.
> Unify devcontainers

- .gitignore
- BUILD
- MODULE.bazel
Update these default bazel modules versions: 
- aspect_rules_py: 1.4.0 -> 1.6.3
- aspect_rules_lint: 1.4.4 -> 1.5.3
- rules_java: 8.13.0 -> 8.15.1
Update our custom bazel modules versions: 
- score_docs_as_code: 1.0.2 -> 1.1.1
- score_process: 1.1.1 -> 1.1.2
Integrate score_tooling and change the integration of all its used sub-modules
Note: After the update ide_support, docs build and tests are working well. 
close: https://github.com/eclipse-score/score/issues/1639
> Update default and custom Bazel modules

- docs/design_decisions/DR-002-infra.md
Large systems often span multiple repositories. Each repository can look “green” on its own, yet problems only show up when everything is combined. These late surprises slow down development and make debugging painful.  
DR-002 turns a collection of separate repositories into a system that behaves like a single, continuously tested whole — ensuring the main line is always integrable across all components.
- Every change in any repository is tested **in combination with the rest of the system**, not just in isolation.  
- There are **two testing layers**:  
- a **fast feedback loop** (lightweight tests that run on every pull request),  
- and a **deeper validation** (heavier tests run after merges or on a schedule).  
- This setup guarantees that developers can trust the system as a whole …
> DR-002-Infra: Integration Testing in a Distributed Monolith

- docs/features/communication/docs/requirements/index.rst
Added extensions to cross-vm requirements (sharing & streaming)
Frank Scholter Peres <frank.scholter_peres@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH
[Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)
> added additional requirements

- .github/actions/deploy-versioned-pages/action.yml
Display a warning message in PR that docs
might not be displayed properly if gh-pages size > 950MB.
Related: https://github.com/eclipse-score/score/issues/1461
> ci: Warn on gh-pages branch size
